### ISSUE TITLE
Can`t build with Visual Studio 2019

### ISSUE THREAD

**Issue by remiznik** [alipbcs/ZetaRay#1]
Several problems with build solution. 

1. with error C2641: cannot deduce template arguments for 'fastdelegate::FastDelegate1'
2. ZetaRay\Tools\BCnCompressglTF\BCnCompressglTF.cpp(11,10): fatal error C1083: Cannot open include file: 'json/json.hpp': No such file or directory

**Comment by alipbcs** [comment]
I'll try to reproduce these with VS 2019.

**Comment by alipbcs** [comment]
Ok, I was able to reproduce the issue in VS 2019 and pushed a fix. Give it a try and let me know if the issue persists.

**Comment by remiznik** [comment]
Fixed.
