### ISSUE TITLE
Fatal error: PipelineStateLibrary.cpp: 146 --- When switching from TAA to FSR2 back and forth 

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#11]
I'm getting a fatal error when switching between TAA et FSR2 two times. I can reproduce it everytime.

Steps to reproduce:

- Start
- Switch from TAA to FSR2
- Switch back to TAA
- Switch back to FSR2
- Crash

![image](https://github.com/user-attachments/assets/495d049d-7ab4-48c1-a60b-c6b1b3634fd6)

**Comment by alipbcs** [comment]
I can't repoduce this on two different systems. I switched many times between TAA and FSR2 and it didn't crash. 

Seems like another hardware-specific issue. Would it be possible for you to test on a different system?

**Comment by TomClabault** [comment]
I don't have another hardware-ray-tracing capable system unfortunately. 

D3D12 NVIDIA drivers don't have a software ray tracing fallback in case the GPU doesn't have hardware ray-tracing right?

**Comment by alipbcs** [comment]
D3D12 has a ray tracing fallback layer, but it's not maintained anymore and requires linking with separate libraries.

**Comment by alipbcs** [comment]
I think I figured out the issue with this one. Could you pull the latest commit and give it another try?

**Comment by TomClabault** [comment]
Yep, looks like it's working now!

**Comment by TomClabault** [comment]
Just curious, why was it not happening on your side? How was it hardware specific?

**Comment by alipbcs** [comment]
I cache the compiled shaders on disk to speed up subsequesnt runs. This issue only occured when the cache wasn't found on disk and I happened to have a cache from prior runs. Once I manually deleted the cache, I was able to reproduce the bug. It wasn't hardware specific.
