### ISSUE TITLE
Most of the 3D geometry is dark with TAA enabled

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#12]
![image](https://github.com/user-attachments/assets/6999b855-d963-4ce3-9ced-76c96f107b30)

Screenshot just after starting the application, TAA is enabled by default. The sky in the background isn't black but most of the cornell box is. I guess that's because that's the only place where TAA reprojects things.

Switching to FSR "fixes" the issue:

![image](https://github.com/user-attachments/assets/81fc90e5-0a6e-4f61-af6d-cf4ac0e94027)

System: Windows 11 + RX 7900 XTX, Drivers v. 24.6.1

**Comment by alipbcs** [comment]
The Cornell Box scene that you're using is different that the one that's in the repo. Could you provide a link to it so I can test it on my end?

**Comment by TomClabault** [comment]
[Here](https://github.com/TomClabault/HIPRT-Path-Tracer/tree/main/data/GLTFs) you go. It's the `cornell_pbr.gltf`. 

I also have the same issue with the original cornell box.

**Comment by TomClabault** [comment]
Just noticed that the same thing happens with "None" as the anti-aliasing method.

**Comment by alipbcs** [comment]
I tested that scene with and without TAA on two different systems and it rendered ok. It seems the problem happens only on certain hardware. Unfortunately, there's not much I can do on my end to fix these type of issues.

![2](https://github.com/user-attachments/assets/19ec530c-f54d-4b73-9331-f02bdd1c6c1c)

**Comment by TomClabault** [comment]
Can I try something on my end maybe?

**Comment by alipbcs** [comment]
At least identifying the problematic shader shouldn't be hard, try this:

On the settings window, go to Display and change Output to BaseColor. If there is darkening, then g-buffers are not rendering correctly. If not, go to Compositing and disable "Direct (Emissives)" and "Indirect" one by one and see which one has the darkening. The final image is the composit of these two plus sky, which is rendering correctly, so it has to be one of the passes above.

**Comment by TomClabault** [comment]
The debug views in "Display" are all correct. 

The issue seems to come from both the direct (emissives) and indirect. Having either of these two active gives the black fringes.

Direct (Sky) seems to work as intended and it adds on top of the black render:

![image](https://github.com/user-attachments/assets/71262e59-d586-4e66-a9c4-ea3a2a5b9e8b)

I tried playing with the parameters under "Direct lighting" but couldn't find any that makes to black stuff go away.

**Comment by alipbcs** [comment]
I see. This is a really odd situation, if something had gone wrong with those two shaders, then the issue should've persisted with FSR2.

Next would be taking a capture with PIX and debugging the code, but that would be a lot of work and requires being familiar with the codebase. It seems this issue doesn't have a trivial fix.

**Comment by TomClabault** [comment]
Would sharing a capture I made with PIX help?

**Comment by alipbcs** [comment]
Yes, that would definitely help. If possible, use the debug build as it has extra debug info.

**Comment by TomClabault** [comment]
It doesn't seem like I can make a capture. I started ZetaLabd with PIX but capturing just hangs forever. If I then put ZetaLabd in the foreground (just click on the window to focus it instead of having the focus on PIX), it crashes after ~5s.

I tried with RenderDoc too but some ImGui error prevents me from even starting the app in RenderDoc

Not sure what else I can try?

**Comment by alipbcs** [comment]
Crashing is specific to PIX version 2405.15 (latest as of now). It never crashed with older versions for me. If you happen to be using that version, could you try an older one? Note that you can have multiple versions of PIX installed side-by-side.

BTW, RenderDoc currently doesn't support ray tracing.

**Comment by TomClabault** [comment]
[Here](https://we.tl/t-ubuWMFOOMZ) is a WeTransfer link of my PIX capture.

Do you need anything else to be able to read the capture on your end or is that single file enough?

**Comment by alipbcs** [comment]
Just the capture file works, thanks!

The capture shows the g-buffers are wrong as the BVH wasn't built correctly. Check the screenshot below: the top half is how it looks for me and the bottom half is yours. The BVH has to contain 5 triangle meshes, but it's empty. This suggests the problem is on the CPU side where the BVH is built.

</br>

![1](https://github.com/user-attachments/assets/c923095d-992f-4683-88f5-f4d80bf8e723)

</br>

Next would be debugging the code that builds the BVH if you're up for it. The relevant code is in the file Source/ZetaCore/RayTracing/RtAccelerationStructure.cpp and function StaticBLAS::Rebuild(). The for loop in the lines 63-96 should add 5 triangle meshes, but apparently it's adding none or the execution doesn't reach there for some reason. Would you be able to add a breakpoint at the start of that function and step through the code and see where things go wrong?

**Comment by TomClabault** [comment]
I'll have a look at it.

Just a quick question: why can wee see something at all (looking at the screenshots of the first comment of this issue) if the BVH isn't built properly?

Also, the G buffers look fine?

![image](https://github.com/user-attachments/assets/d101f78d-1b92-4482-a69e-6af5e5c13011)

![image](https://github.com/user-attachments/assets/6301a944-ffdb-4de2-9cf8-af8e9faef619)

![image](https://github.com/user-attachments/assets/31cc56ca-a2ac-4b6a-9ce3-0c200f7ec7e5)

**Comment by alipbcs** [comment]
Yeah, that's odd. When I replay the capture, all the g-buffers are blank, and the final render is just the sky. Looks like capturing on one GPU and replaying it on another GPU is incompatible.

So the BVH stuff isn't the problem. Back to square one I guess :(

**Comment by TomClabault** [comment]
After trying again on commit [1f93e19](https://github.com/alipbcs/ZetaRay/commit/1f93e19440f8225517f01759706370fe0a2aa214), this seems fixed.
