### ISSUE TITLE
Disabling/enabling Compositing->Inscattering back and forth yields "It's assumed that every PSO is loaded at most one time"

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#13]
Steps to reproduce:

- Start
- Enable Compositing / Inscattering
- Disable Compositing / Inscattering
- Enable Compositing / Inscattering
- Crashes with:

![image](https://github.com/user-attachments/assets/0d82c511-23ea-4069-b228-6b1313b6522f)

**Comment by alipbcs** [comment]
Ok, I was able to reproduce this on my end. The problem is that I'm trying to load a shader that's been loaded already. I'll push a fix.
