### ISSUE TITLE
HRESULT: 887a0001 Zetaray\Source\ZetaCore\Core\Device.cpp: 169

### ISSUE THREAD

**Issue by Zhou1539** [alipbcs/ZetaRay#14]
Thanks for your code, but I have encountered some runtime errors. I cloned the [latest commit](https://github.com/alipbcs/ZetaRay/tree/3d29464ccbfc99e62a9ab052183b52750581ecd8) but after compiling it successfully, I got several runtime problems.

- The first is an Assertion fail and it happens randomly: 
![image](https://github.com/user-attachments/assets/ef183c97-2d27-4b68-af94-e252ab912722)

- IDXGISwapChain3.SetMaximumFrameLatency()
``` 
void DeviceObjects::CreateSwapChain(ID3D12CommandQueue* directQueue, HWND hwnd, int w, 
    int h, int numBuffers, DXGI_FORMAT format, int maxLatency)
{
    DXGI_SWAP_CHAIN_DESC1 desc{};
    desc.Width = w;
    desc.Height = h;
    desc.Format = format;
    desc.Stereo = false;
    desc.SampleDesc.Count = 1;
    desc.SampleDesc.Quality = 0;
    desc.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    desc.BufferCount = numBuffers;
    desc.Scaling = DXGI_SCALING_NONE;
    desc.AlphaMode = DXGI_ALPHA_MODE_IGNORE;
    desc.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
    desc.Flags = m_swapChainFlags;

    IDXGISwapChain1* swapChain;
    CheckHR(m_dxgiFactory->CreateSwapChainForHwnd(directQueue, hwnd, &desc, 
        nullptr, nullptr, &swapChain));
    CheckHR(swapChain->QueryInterface(IID_PPV_ARGS(m_dxgiSwapChain.GetAddressOf())));
    swapChain->Release();

    CheckHR(m_dxgiSwapChain->SetMaximumFrameLatency(maxLatency));
    m_frameLatencyWaitableObj = m_dxgiSwapChain->GetFrameLatencyWaitableObject();
}
```
![image](https://github.com/user-attachments/assets/2ca29d9d-5769-4c55-9009-88b574679751)

In the Zetaray\Source\ZetaCore\Core\Device.cpp I got the second problem that the ```m_swapChainFlags``` should be DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT(64) but it becomes 2048 when I go to the line 169 ``` CheckHR(m_dxgiSwapChain->SetMaximumFrameLatency(maxLatency)); ```
I solved this problem by doing an OR operation with DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT
``` desc.Flags = m_swapChainFlags | DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT; ```

- After I solved the second problem, I got an Access violation reading in ZetaRay\External\concurrentqueue\concurrentqueue.h Line 1408
![image](https://github.com/user-attachments/assets/2d58b418-3fa5-431c-9844-f173f63d26f3)
I guess this is caused by multithread? It's so weird.
Do you have any ideas?

**Comment by jichumao** [comment]
Same Problem here, tested on RTX4090 & 13700K

**Comment by alipbcs** [comment]
Thanks for reporting the issues. For the second issue:

1. 2048 corresponds to DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING. I check for hardware support for tearing and do a bitwise or with the default value (DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT). Could you try commenting out the lines 113-114 in Device.cpp and see if it helps?

![1](https://github.com/user-attachments/assets/0b3ec5aa-aec5-4eec-ba91-38f9b8ac0dd8)

2. The debug layer might be able to catch the issue. Try uncommenting line 6 in Device.cpp and see if it reports any issues.

![2](https://github.com/user-attachments/assets/35c798ef-21ad-4629-b4bf-e67156f37fa3)

For the first issue,  could you change the assertion in line 1345 in Win32.cpp to the following and let me know the output when the assertion is triggered?

```cpp
Assert(ret != -1, "thread index was not found.\n#num_threads: %d\nthread_id: %u,\nexisting: %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u, %u", 
    g_app->m_processorCoreCount, id,
    g_app->m_threadIDs[0],
    g_app->m_threadIDs[1],
    g_app->m_threadIDs[2],
    g_app->m_threadIDs[3],
    g_app->m_threadIDs[4],
    g_app->m_threadIDs[5],
    g_app->m_threadIDs[6],
    g_app->m_threadIDs[7],
    g_app->m_threadIDs[8],
    g_app->m_threadIDs[9],
    g_app->m_threadIDs[10],
    g_app->m_threadIDs[11],
    g_app->m_threadIDs[12],
    g_app->m_threadIDs[13],
    g_app->m_threadIDs[14],
    g_app->m_threadIDs[15]);
```

**Comment by alipbcs** [comment]
I think I figured out the problem with the first issue. Could you pull the latest commit and give it another try?

**Comment by jichumao** [comment]
Cool! I think it is working now!
![image](https://github.com/user-attachments/assets/3c45e285-a326-4e91-a110-cc7267e67b25)

**Comment by jichumao** [comment]
![image](https://github.com/user-attachments/assets/1b4239a6-017e-4fae-a056-bacd1756e311)
![image](https://github.com/user-attachments/assets/189ebc4a-cbff-49f7-9eb9-9beb080eaf7d)

Not sure why this happened, but there is some random rendering issue with big resolution size(like 4K)

**Comment by alipbcs** [comment]
> ![image](https://private-user-images.githubusercontent.com/74147893/382529858-1b4239a6-017e-4fae-a056-bacd1756e311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDY0ODgsIm5iZiI6MTczMDYwNjE4OCwicGF0aCI6Ii83NDE0Nzg5My8zODI1Mjk4NTgtMWI0MjM5YTYtMDE3ZS00ZmFlLWEwNTYtYmFjZDE3NTZlMzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDAzNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTY1ZDkzMDgxOTY1NDBmYjQ4OGU3MDRiMTIyNDNmNWJhNzNiM2M5MmFhYTdhYzUxZWQxOTY3ZjFiZDkxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W2l8fBZvQ2boaTvONugnWs1bHGL0-FOmP5PVaZsQFq4) ![image](https://private-user-images.githubusercontent.com/74147893/382529917-189ebc4a-cbff-49f7-9eb9-9beb080eaf7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDY0ODgsIm5iZiI6MTczMDYwNjE4OCwicGF0aCI6Ii83NDE0Nzg5My8zODI1Mjk5MTctMTg5ZWJjNGEtY2JmZi00OWY3LTllYjktOWJlYjA4MGVhZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDAzNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MGY5YWQ1NDE4NzY4ZWM1MjA2YjdlNzk4MTdlYjRhZjdkZjc3OTAyYzhmNmQzOTVjYWM3NTA3Y2I5NWI1YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DAtuW3bvlfMcNmzNL5kmGooAe2iBkeDaevZnPJyzA2s)
> 
> Not sure why this happened, but there is some random rendering issue with big resolution size(like 4K)

Are the black bars always there or do they come and go randomly?

**Comment by jichumao** [comment]
It seems to have different effects at different resolutions, at some resolutions it's a fixed black bar, at some resolutions it's the effect of Figure 2, but when the resolution roughly < 1080p, it looks alright.

**Comment by alipbcs** [comment]
Could you try the following UI options and let me know how the black bars are affected?

1. In Settings->Renderer->Anti-Aliasing, change Method from "TAA" to "None"
2. In Settings->Renderer->Compositing, uncheck "Direct (Sky)" and "Indirect" separately and see if the problem is isolated to one. With both unchecked, any non-sky pixel should be black.
3. In Settings->Renderer->Display, change Output from "Default" to "BaseColor"

**Comment by jichumao** [comment]
![image](https://github.com/user-attachments/assets/7de944eb-375a-48a6-974c-1209dbbbecb6)
![image](https://github.com/user-attachments/assets/32865269-11b7-4700-b0aa-d6de49c941b7)
Direct sky light ON and OFF

The other options don't affect the bar too much. And base color renders correctly

**Comment by jichumao** [comment]
with both unchecked, sky rendered correctly

**Comment by alipbcs** [comment]
I see. This seems to be the same issue as #12. 

G-buffers are rendered correctly, but there's a bug that affects the lighting passes. I'd have to take a GPU capture and debug the shaders, but since I can't reproduce the issue on my system, sadly there's not much I can do to help.

**Comment by alipbcs** [comment]
@Zhou1539 Have you had a chance to try the latest commit and see if it fixes one of the crashes for you?

**Comment by Zhou1539** [comment]
Yes, it works well in my case and I didn't meet the bug @jichumao has mentioned.

**Comment by alipbcs** [comment]
> Yes, it works well in my case and I didn't meet the bug @jichumao has mentioned.

Glad to hear it's working! Is the second issue (SetMaximumFrameLatency) fixed too?

**Comment by Zhou1539** [comment]
> > Yes, it works well in my case and I didn't meet the bug @jichumao has mentioned.
> 
> Glad to hear it's working! Is the second issue (SetMaximumFrameLatency) fixed too?

Yes, I think it is because of some unexpected race condition and you fixed it.

**Comment by alipbcs** [comment]
@jichumao I was finally able to reproduce the issue. As you mentioned, it only happened at higher resolutions and since my monitor is 1080p, it had never occured for me. After manually resizing the window past the desktop resolution, the black bars appeared.

Could you try the latest commit and see if the issue is fixed for you?

**Comment by jichumao** [comment]
Awesome! It has been fixed
