### ISSUE TITLE
BCnCompressglTF.cpp(13,10): error C1083: Cannot open include file: 'cgltf/cgltf_write.h': No such file or directory

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#16]
So I tried preprocessing one of my scene with BCnCompressglTF. For that I needed the `BCnCompressglTF`  exe file to be able to follow the instructions of the README so I thought that I had to build the `BCnCompressglTF` target of the Visual Studio solution:

```
mkdir build
cd  build
cmake ..

Open Visual Studio solution
Rebuild BCnCompressglTF
```

But this yielded the title error about that missing CPP file. Is this a setup error on my end or is this a file missing from the repo?

**Comment by alipbcs** [comment]
Could you delete the ./External/cgltf directory and run cmake again?

**Comment by TomClabault** [comment]
Okay yep, now I can preprocess scenes 👍
