### ISSUE TITLE
"Negative  scale factors are not supported" when trying to load my "the-white-room" scene

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#17]
Steps to reproduce:

- Clone [1f93e19](https://github.com/alipbcs/ZetaRay/commit/1f93e19440f8225517f01759706370fe0a2aa214)
- `mkdir build && cd build && cmake ..`
- Open Visual Studio Solution
- Build `BCnCompressglTF` && `ZetaLab`
- cd ../bin
- [Download ](https://mega.nz/file/Ekx1lQib#Z8142LqMtMxfMzoz7K4RuZ6fQgvFPbqcdbO2_Sirvk8) "the white room" test scene I used for this issue.
- Extract the files to Assets/
- ./BCnCompressglTFd.exe ../Assets/the-white-room.gltf
- ./ZetaLabd.exe ../Assets/the-white-room_zeta.gltf

![image](https://github.com/user-attachments/assets/3df19c07-8c87-4022-92b8-94a82f4b94eb)

**Comment by alipbcs** [comment]
I have to decompose transformation matrices into translation, rotation, and scaling. When there are negative scales, decomposition becomes more complicated and is currently not supported.

The workaround is to import in Blender, apply the scale (so it becomes 1.0) and then export back. I've attached the result for this scene.
[white_room.zip](https://github.com/user-attachments/files/18141791/white_room.zip)

**Comment by TomClabault** [comment]
How did you find the object that had a negative scale?

**Comment by alipbcs** [comment]
I printed the name of nodes that had negative scales. Node names correspond to object names in Blender.

**Comment by TomClabault** [comment]
I guess that fixes it.
