### ISSUE TITLE
Camera acting up and incontrollable on custom scene

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#18]
I downloaded your [white-room](https://github.com/user-attachments/files/18141791/white_room.zip) fixed from a previous issue and ran the BCn compress  utility on it. Opening the scene in ZetaLab and trying to move the camera results in the camera spining very fast on its own.

[Video](https://youtu.be/Ary6n_xbUtE)

Setting all the sliders of the Camera -> Motion menu to 1.0f seems to fix the issue. This was on a high DPI monitor if that's relevant. Does not happen on the `Cornell/cornell.gltf` scene of the repo.

**Comment by alipbcs** [comment]
Yeah, I probably need to use a heuristic for the defaults that takes scene scales into account.

Also, from the video, frame time is around 60 ms!!! Is this at 4k?

**Comment by TomClabault** [comment]
Yes, that was at 3800x2000 on a 7900XTX.

**Comment by alipbcs** [comment]
Input latency should be really bad. Could you resize the window to around 1080p and take a screenshot of GPU timings? Some of the numbers seems oddly high compared to what I'm used to.

**Comment by TomClabault** [comment]
Here you go:

![image](https://github.com/user-attachments/assets/ade74d17-78a1-4206-b7b5-0913beadd7ee)

**Comment by TomClabault** [comment]
Oh and by the way, resizing the window to 1080p fixes camera acting up.

**Comment by alipbcs** [comment]
Thanks! Some of these are way higher than I'm getting with RTX 3070. According to Blender GPU benchmarks, you GPU should be around 33% faster than mine.

![1](https://github.com/user-attachments/assets/1e24df3b-42a5-4d2c-aa12-ea82d5062104)

**Comment by TomClabault** [comment]
Hmmm indeed the tracing looks super slow. Even though NVIDIA has better ray tracing hardware 30xx ray tracing should be somewhat similar to RDNA3 rt hardware no? At least not by 2x I believe

**Comment by TomClabault** [comment]
Also, do you know if Blender Benchmarks use HIPRT? I can only see "HIP" in [the charts](https://opendata.blender.org/) and not HIPRT. But I can see OptiX.

**Comment by TomClabault** [comment]
> Does HIP support hardwared accelerated RT?

HIP is the equivalent to CUDA.
HIPRT is the equivalent to OptiX.

HIP doesn't support hardware accelerated RT. This is probably  because HIPRT is still experimental in Blender so maybe it hasn't made its way to the Blender Benchmarks executable yet.

**Comment by alipbcs** [comment]
> > Does HIP support hardwared accelerated RT?
> 
> HIP is the equivalent to CUDA. HIPRT is the equivalent to OptiX.
> 
> HIP doesn't support hardware accelerated RT. This is probably because HIPRT is still experimental in Blender so maybe it hasn't made its way to the Blender Benchmarks executable yet.

Oh ok I see. So 7900XTX should be much faster than 33%, which makes the situation even more odd.
