### ISSUE TITLE
Codespace api requires Windows developer mode

### ISSUE THREAD

**Issue by yhyu13** [alipbcs/ZetaRay#2]
Hi,

Just found out that some of the api requires deverloper mode enable for the Windows operating system.

![devenv_k5C0Si5u9C](https://github.com/alipbcs/ZetaRay/assets/19365678/e9596a3a-31d6-4ed0-ad36-ccab2546403f)

Mentioned by Microsoft here : https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-setstablepowerstate

I think this should be noted by users

**Comment by yhyu13** [comment]
I was trying to do a debug build, where that api call was triggered. I guess you were in developer mode, right?

**Comment by alipbcs** [comment]
Yes, that method requires the system to be in developer mode. Implicitly assuming developer mode is considered poor practice. I'll add a macro around it to disable it by default.
