### ISSUE TITLE
Any ways to turn off ReSTIR DI?

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#20]
And use no NEE/classic NEE/MIS/RIS instead for example?

If this cannot be done through the UI interactively, modifying the code is okay as long there aren't too many steps involved.

**Comment by alipbcs** [comment]
Yes, in "Direct Lighting", uncheck "Temporal Resample" and "Spatial Resample". This turns it into typical MIS with light and bsdf sampling.

**Comment by TomClabault** [comment]
Awesome!

**Comment by TomClabault** [comment]
Another quick question (not opening an issue for that): does "GBuffer" correspond to the time taken by camera rays to intersect the scene + filling the GBuffer?

![image](https://github.com/user-attachments/assets/b3bcf1b0-4a63-403c-8c8e-a2639807c63d)

**Comment by alipbcs** [comment]
Yes, exactly.

That seems reasonable. At 1080p, it usually takes around 1 ms for me. Camera rays are very coherent, so they should be efficient to trace. Performance is mainly impacted by objects with alpha textures, which require any-hit shaders. If the screen is filled with those type of objects, then it can get a few times slower.

**Comment by TomClabault** [comment]
Do you roughly remember the performance impact of going with a two-level BVH versus 1 level (one gigantic BLAS for all the triangles)? Or does D3D12 has no other option than going 2-levels?

**Comment by alipbcs** [comment]
Only two levels are possible with DXR - one TLAS containing instances of BLASes. I start with one BLAS with all the scene geometry and the corresponding single TLAS instance. When some object is moved for the first time, I extract it from the original BLAS, build a separate BLAS for it (so it can be transformed independently), and rebuild and compact the first BLAS. I haven't measured the performance with a separate BLAS for every object.

Yes, 1 ms for bistro on RTX 3070. It's around 1 ms for most scenes.

**Comment by TomClabault** [comment]
Oh I see that's interesting!

Now I noticed that in my renderer, the camera rays take 1.6ms on the bistro. At 720p. Your renderer takes ~0.4ms at the same settings and roughly same point of view.

I wonder what that is. What I'm eventually missing is BVH compaction for now but I don't expect this to multiply basically raw ray tracing performance by 4x.

Any intuitions maybe?

The occupancy in my camera rays kernel is at its maximum which suggests that this is purely shader-operations-bound. My renderer isn't written with DX12 but it uses HIPRT so I do have access to hardware ray tracing. I'm using the fast trace BVH setting with triangle splits and triangle pairing so performance should be good here.

The HIPRT paper (https://gpuopen.com/download/publications/HIPRT-paper.pdf) also shows that HIPRT's traversal performance is at the very least Vulkan level (which I assume is the exact same performance as DX12) but is more like 20% better on average (Table 1 of the paper). So I assume that the performance gap doesn't come from the BVH (unless it's all because of the compaction but 4x the perf?)

Any intuitions maybe?

I think I'll also try to completely strip my camera rays kernel to benchmark raw traversal performance and see how much time that takes. To get a baseline.

**Comment by alipbcs** [comment]
Interesting, what you described reminded me of this [paper](https://dl.acm.org/doi/pdf/10.1145/3550454.3555463) (RT framework with multiple backends). From the benchmarks (figure 6), dx12 is around 2x faster than optix. The authors attribute that to usage of inline RT in dx12. From my experience on RTX 3070 across multiple workloads, inline was consistently faster - for a regular path tracer, it was almost 2x faster. To my knowledge, inline is not possible with optix. HIPRT seems similar to optix, so maybe it's a similar situation here?

The g-buffer shader itself is relatively simple; trace camera ray, extract material info, compute ray differentials, and store to memory. Beyond RT traversal, I don't think there should be that big of a difference between different implementations. 

Also, if the code is public, I can take a look.

**Comment by TomClabault** [comment]
Ohhh LuisaRT is super interesting. I would probably have written my renderer with that instead of HIPRT if I had known sooner because I regret a bit not having access to NVIDIA's RT hardware with HIPRT.

Also wavefront kernels are consistently slower on the GPU as per Fig. 6? That's a bit sad (but consistent with your own experience).

What is inline ray tracing? Why is OptiX's ray tracing not inline?

> Also, if the code is public, I can take a look
https://github.com/TomClabault/HIPRT-Path-Tracer/blob/PerformanceImprovements/src/Device/kernels/CameraRays.h

I did some experiments and it seems that the G-Buffer filling at the end of the kernel:

```C++
if (intersection_found)
{
    if (ray_payload.material.is_emissive() && hippt::dot(-ray.direction, closest_hit_info.geometric_normal) < 0)
    {
        // TODO necessary? Not already handled by trace_ray() ?
        closest_hit_info.geometric_normal = -closest_hit_info.geometric_normal;
        closest_hit_info.shading_normal = -closest_hit_info.shading_normal;
    }

    render_data.g_buffer.geometric_normals[pixel_index].pack(closest_hit_info.geometric_normal);
    render_data.g_buffer.shading_normals[pixel_index].pack(closest_hit_info.shading_normal);

    render_data.g_buffer.materials[pixel_index] = DevicePackedEffectiveMaterial::pack(ray_payload.material);
    render_data.g_buffer.primary_hit_position[pixel_index] = closest_hit_info.inter_point;
    render_data.g_buffer.ray_volume_states[pixel_index] = ray_payload.volume_state;
}
else
    // Special case when not hitting anything
    //
    // The view directions are reconstructed from the primary hit and the camera position
    // but if we didn't hit anything, there's no primary hit. 
    // 
    // But we're still going to need to be able to reconstruct the view direction 
    // so we're faking the primary hit with the point the ray was directed to instead.
    //
    // If you're wondering: "yeah but then the rest of the ray tracing passes are going to use a wrong primary hit position?"
    //      --> No because the 'camera_ray_hit' indicates whether we have a primary hit or not.
    //          If we don't have a primary hit, we're never going to use the float3 in the 'primary_hit_position'
    //          buffer as an actual position, 
    render_data.g_buffer.primary_hit_position[pixel_index] = ray.origin + ray.direction;
    
render_data.g_buffer.first_hit_prim_index[pixel_index] = intersection_found ? closest_hit_info.primitive_index : -1;

render_data.aux_buffers.pixel_active[pixel_index] = true;
```

on its own takes 0.4ms. That sounds like a lot and I'm not sure how to do better (the `geometric_normals` buffer could be removed but it'll have to stay here for now).

**Comment by alipbcs** [comment]
Yeah, pure wavefront seems slow. A mixture of wavefront and megakernel could be a good option (wavefront for the first N hits, megakernel for the rest).

In inline RT, we can use ray queries in regular shaders without having to set up RT pipelines. So ray generation, closest hit shaders and so on, and shader binding tables (SBT) are not required anymore. There's no longer custom hit shading based on SBT, but it's significanly more convenient and simpler. 

Looking at the code, I think I'm storing even more data such as motion vectors and ray differentials. But one difference is that I'm using textures, whereas you seem to be using buffers.

The goal of g-buffers is to avoid recomputing data that's needed multiple times in subsequent shaders. You seem to be splitting the computation into multiple kernels that require the primary hit data. So material evaluation in the camera ray kernel should be beneficial.

For trace_ray(), how much of the 0.57 ms is just for RT traversal?

**Comment by TomClabault** [comment]
Yeah okay so according to your description, HIPRT is inline RT too. It doesn't have the whole ray tracing pipeline as OptiX (or DX12/Vulkan).

You mean that you're using textures for your G-Buffer data?

> For trace_ray(), how much of the 0.57 ms is just for RT traversal?

Seems to be all of it. 

Oh and by the way, why is ReSTIR DI still taking some time in the "GPU Timings" even with temporal and spatial reuse disabled?

**Comment by alipbcs** [comment]
Cool that HIPRT is also inline. RT pipelines are painful to work with.

Makes sense to use textures for g-buffers. There's a one-to-one correspondence to screen pixels. Memory access would also be more efficient - kernels with 2D thread groups access pixels based on 2D addressing as opposed to linear (better fit for buffers) and textures are optimized for that.

When reuse is disabled, the time taken is just for regular direct lighting without any ReSTIR stuff. Regular direct lighting feeds into the temporal pass of ReSTIR, so they're in the same shader. I don't change the label from "ReSTIR DI" when reuse is disabled, that's probably what makes it confusing.

**Comment by TomClabault** [comment]
> kernels with 2D thread groups access pixels based on 2D addressing ... are optimized for that?

How? I know of the texture cache that helps when reading from multiple adjacent texels of a texture for does that also apply for writes? Any other reason why textures are more optimized for 2D thread groups?

**Comment by alipbcs** [comment]
Textures use tiled or swizzled formats like [Morton code](https://fgiesen.wordpress.com/2011/01/17/texture-tiling-and-swizzling/) to optimize 2D locality. For an 8 by 8 thread group that's accessing corresponding texels, ideally those texels should be close in memory. This way, when a cache line is loaded, we get multiple hits.

The actual layout is actually implementation defined. That's why in Direct3D and Vulkan, there are dedicated APIs for copying data to textures and we can't simply do a memcpy.

G-buffers are data that we plan to access from other shaders such as ReSTIR, denoising, upscalers, etc. Since we use 2D thread groups for those shaders, memory reads from textures would be more efficient.
