### ISSUE TITLE
HDR envmap support?

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#21]
Any ways to load in an HDR/EXR for the environment map?

Also, is the current sky sampled at each bounce? i.e. at each bounce a light direction for the sun's illumination is chosen (or maybe it's just purely directional, only one direction?) and a shadow ray traced for the visibility in that direction.

**Comment by alipbcs** [comment]
Not currently. For now, I do a single scattering estimation of atmosphere scattering each frame and store the results in a small latitude/longitude texture, Supporting custom environment maps would be a matter of replacing that texture with one provided by the user.

Yes, after ReSTIR DI for the first hit, I stochastically choose between the sun and the sky for direct lighting at subsequent hits.

**Comment by TomClabault** [comment]
Hmm, I can't seem to have the sun illuminate the scene though.

![image](https://github.com/user-attachments/assets/7fef5d9f-72e6-4699-a29a-ffb0b35d1007)

**Comment by TomClabault** [comment]
![image](https://github.com/user-attachments/assets/fab05a2b-458c-4cde-8f53-0685ed588bf2)

**Comment by alipbcs** [comment]
The supported light source types are sun and sky or emissives. When the scene has emissive materials, they act as the only light sources. If there are no emissives, then the sun and sky are the light sources.

Since there are emissives in this scene, sun and sky are ignored during lighting.

**Comment by TomClabault** [comment]
Oh okay I see, makes sense.

Also unrelated question that comes to mind about your renderer: you did try ray reordering right? And you the perf gains wasn't worth it iirc. What sorting algorithm did you use and did you try on "complex" scenes such as the Bistro?

**Comment by alipbcs** [comment]
Yeah, I used octahedral mapping of the unit sphere where every direction goes into one of the octants. Afterward, the corresponding rays from each octant are stored contiguously in a buffer for tracing. I only did that for the first indirect bounce. I tested it across various scenes and didn't see any performance improvements.

BTW, I can add a UI option to force lighting from sun and sky and ignore emissives if you'd like.

**Comment by TomClabault** [comment]
> didn't see any performance improvements.

Maybe this lack of speedup comes from the fact that you have a 3070 and so the traversal is already decently fast.

> BTW, I can add a UI option to force lighting from sun and sky and ignore emissives if you'd like.

Yeah sure. Also, would it be difficult to have both the sky & sun and emissives at the same time?

**Comment by alipbcs** [comment]
> Maybe this lack of speedup comes from the fact that you have a 3070 and so the traversal is already decently fast.

Yeah, that's definitely possible.

> Yeah sure. Also, would it be difficult to have both the sky & sun and emissives at the same time?

You can now toggle between them from "Scene->Emissives->Enabled". Let me know if there are any issues.

Both at the same time would unfortunately take a lot more work. I'll have to support it at some point in the future, but for now it's not possible.

**Comment by TomClabault** [comment]
This seems to be working great! How come using the sun & sky is much faster than emissives?

60FPS with emissives
84FPS with the sun & sky

**Comment by alipbcs** [comment]
Glad it's working!

The path tracing shader seems faster with sun/sky. Maybe because during direct lighting, many points end up choosing the sun, resulting in more coherent shadow rays. Also, emissives require reading more data from memory, such as triangle position, emissive textures, etc.
