### ISSUE TITLE
build fails with  Tests\TestMath.cpp(376,23): error C2039: 'DegreeToRadians': is not a member of 'ZetaRay::Math'

### ISSUE THREAD

**Issue by kyamant** [alipbcs/ZetaRay#9]
Both Release and Debug builds fail:
Tests\TestMath.cpp(376,23): error C2039: 'DegreeToRadians': is not a member of 'ZetaRay::Math'

**Comment by alipbcs** [comment]
Thanks for reporting the issue. Looks like I forgot to refactor the tests after a recent change. I'll push a fix.
